import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy.schema import CreateTable
import sys

# ================= 配置区域 =================
# 数据库路径
DB_URI = 'sqlite:///workorders.db'
# 输出文件
OUTPUT_FILE = 'models_autogenerated.py'
# ===========================================

# 定义简单的类型映射，将 SQL 类型转为 Flask-SQLAlchemy 代码
def get_column_type(column):
    try:
        # 获取字段类型的字符串表示，例如 INTEGER, VARCHAR(255)
        col_type = str(column.type)
        
        if 'INTEGER' in col_type:
            return 'db.Integer'
        elif 'VARCHAR' in col_type or 'TEXT' in col_type:
            # 简单处理：如果是 TEXT 或者很长的 VARCHAR，用 db.Text，否则 db.String
            if 'TEXT' in col_type:
                return 'db.Text'
            return 'db.String(255)' 
        elif 'DATETIME' in col_type:
            return 'db.DateTime'
        elif 'DATE' in col_type:
            return 'db.Date'
        elif 'BOOLEAN' in col_type:
            return 'db.Boolean'
        elif 'NUMERIC' in col_type or 'DECIMAL' in col_type:
            return 'db.Numeric(10, 2)'
        elif 'FLOAT' in col_type or 'REAL' in col_type:
            return 'db.Float'
        else:
            # 兜底：如果是未知类型，直接保留原样或转为 String
            return f"db.String(255) # Warning: Unknown type {col_type}"
    except Exception:
        return 'db.String(255)'

def generate_code():
    # 1. 初始化一个临时的 Flask App 来连接数据库
    app = Flask(__name__)
    app.config['SQLALCHEMY_DATABASE_URI'] = DB_URI
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    
    # 2. 初始化 SQLAlchemy 并反射数据库
    db = SQLAlchemy(app)
    
    print(f"正在读取数据库 {DB_URI} ...")
    with app.app_context():
        # 反射：让 SQLAlchemy 自动读取所有表结构
        db.reflect()
        
        # 准备写入文件
        lines = []
        lines.append("# coding: utf-8")
        lines.append("from apps.tools.extensions import db")
        lines.append("from datetime import datetime")
        lines.append("\n")

        # 获取所有表名并排序
        table_names = sorted(db.metadata.tables.keys())
        
        if not table_names:
            print("❌ 错误：数据库中没有发现任何表！请检查路径是否正确。")
            return

        print(f"发现 {len(table_names)} 张表，开始生成代码...")

        for table_name in table_names:
            # 跳过 sqlite 系统表
            if table_name.startswith('sqlite_'):
                continue
                
            table = db.metadata.tables[table_name]
            
            # 生成类名：将 user_details 转换为 UserDetail (大驼峰)
            class_name = "".join(x.title() for x in table_name.split('_'))
            
            lines.append(f"class {class_name}(db.Model):")
            lines.append(f"    __tablename__ = '{table_name}'")
            lines.append("")
            
            # 遍历列
            for column in table.columns:
                col_def = []
                col_def.append(get_column_type(column))
                
                # 主键
                if column.primary_key:
                    col_def.append("primary_key=True")
                    # SQLite 的 Integer Primary Key 默认都是自增的
                    if 'Integer' in str(column.type):
                        col_def.append("autoincrement=True")
                
                # 唯一约束
                if column.unique:
                    col_def.append("unique=True")
                
                # 可空性 (如果不是主键，且不可空)
                if not column.nullable and not column.primary_key:
                    # SQLite 有时候对 nullable 处理比较宽松，这里可以选择性加
                    # col_def.append("nullable=False")
                    pass
                
                # 默认值 (简单处理，复杂的 SQL 默认值很难完美转换)
                if column.server_default:
                    # 尝试识别 CURRENT_TIMESTAMP
                    if 'CURRENT_TIMESTAMP' in str(column.server_default):
                        col_def.append("default=datetime.now")
                
                # 拼接
                line = f"    {column.name} = db.Column({', '.join(col_def)})"
                lines.append(line)
            
            lines.append("\n")
            print(f"  - 已处理表: {table_name} -> class {class_name}")

        # 写入文件
        with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
            f.write("\n".join(lines))
        
        print(f"\n✅ 成功！模型文件已生成: {os.path.abspath(OUTPUT_FILE)}")
        print("请打开文件检查，并根据需要微调字段类型。")

if __name__ == "__main__":
    generate_code()